name: vehicle_management
description: A multi-tenant, multi-vehicle mobile application with petrol and service log tracking and analytics dashboards.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fl_chart: ^0.66.0
  uuid: ^4.3.3
  intl: ^0.19.0
  mongo_dart: ^0.10.8
  flutter_dotenv: ^6.0.1
  path_provider: ^2.1.5
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.jpg
